metric: COCO
num_classes: 3

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train_new.json
    dataset_dir: dataset/camera/PaddleDataset
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: dataset/camera/PaddleDataset

TestDataset:
  !ImageFolder
    anno_path: annotations/val.json
