_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/cascade_fpn_reader.yml',
]

architecture: CascadeRCNN
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNeXt101_vd_64x4d_pretrained.tar
load_static_weights: True

weights: checkpoints/cascade_rcnn_dcn_x101_vd_64x4d_bifpn_3x_coco/model_final

snapshot_epoch: 12
epoch: 36
LearningRate:
  # base_lr: 0.01
  base_lr: 0.0025 # gpu 4
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    #milestones: [8, 11]
    milestones: [28, 34]
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000


CascadeRCNN:
  backbone: ResNet
  neck: BiFPN
  rpn_head: RPNHead
  bbox_head: CascadeHead
  # post process
  bbox_post_process: BBoxPostProcess

ResNet:
  # for ResNeXt: groups, base_width, base_channels
  depth: 101
  groups: 64
  base_width: 4
  base_channels: 64
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4
  dcn_v2_stages: [1,2,3] # C3-C5

BiFPN:
  in_channels: [256, 512, 1024, 2048]
  out_channels: 256
  num_cell: 1
  freeze_norm: False
  norm_type: bn

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[8], [16], [32], [64], [256]] 
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
    topk_after_collect: True
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

BBoxAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  cascade_iou: [0.5, 0.6, 0.7]
  use_random: True

CascadeHead:
  head: CascadeTwoFCHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner

CascadeTwoFCHead:
  mlp_dim: 1024

BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [30.0, 30.0, 15.0, 15.0]
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.04
    nms_threshold: 0.7
    normalized: true

metric: COCO
num_classes: 3

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train_new.json
    dataset_dir: D:\PaddleDataset
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: D:\PaddleDataset

TestDataset:
  !ImageFolder
    anno_path: annotations/image_info_val.json