_BASE_: [
  '_base_/coco_detection.yml',
  '_base_/optimizer_3x.yml',
  '_base_/multi_scale_reader_aug.yml',
]
architecture: CascadeRCNN
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
load_static_weights: True
weights: output/cascade_rcnn_r50_fpn_3x/model_final

use_gpu: true
log_iter: 20
save_dir: output
snapshot_epoch: 6

CascadeRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: CascadeHead
  # post process
  bbox_post_process: BBoxPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4

FPN:
  out_channel: 256

RPNHead:
  anchor_generator:
    # N = aspect_ratios * anchor_sizes
    aspect_ratios: [0.5, 1.08, 1.5, 2.0]
    anchor_sizes: [[8], [16], [32], [64], [128]]
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
    topk_after_collect: True
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.70
    pre_nms_top_n: 1000
    post_nms_top_n: 1000


CascadeHead:
  head: CascadeTwoFCHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner
  bbox_loss: DIouLoss
  cls_loss: SoftmaxFocalLoss

DIouLoss:
  loss_weight: 10.0
  use_complete_iou_loss: True # ciou

BBoxAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  cascade_iou: [0.5, 0.6, 0.7]
  use_random: True

CascadeTwoFCHead:
  out_channel: 1024

BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [30.0, 30.0, 15.0, 15.0]
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.02 # smaller than 0.04
    nms_threshold: 0.73
    normalized: true


# TrainDataset:
#   !COCODataSet
#     image_dir: train
#     anno_path: annotations/train_new.json
#     dataset_dir: D:\PaddleDataset
#     data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

# EvalDataset:
#   !COCODataSet
#     image_dir: val
#     anno_path: annotations/val.json
#     dataset_dir: D:\PaddleDataset
