_BASE_: [
  '_base_/coco_detection.yml',
  '_base_/optimizer_2x.yml',
  '_base_/multi_scale_reader_aug.yml',
]
architecture: CascadeRCNN
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNeXt101_vd_64x4d_pretrained.tar
load_static_weights: True
weights: output/cascade_rcnn_dcn_x101_vd_64x4d_fpn_20e_class12/model_final

use_gpu: true
log_iter: 20
save_dir: output
snapshot_epoch: 5


CascadeRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: CascadeHead
  # post process
  bbox_post_process: BBoxPostProcess

ResNet:
  depth: 101
  groups: 64
  base_width: 4
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4
  dcn_v2_stages: [1,2,3]

FPN:
  out_channel: 256

RPNHead:
  anchor_generator:
    # N = aspect_ratios * anchor_sizes
    aspect_ratios: [0.5, 1.08, 1.48, 2.0]
    anchor_sizes: [[8], [16], [32], [64], [128]]
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
    topk_after_collect: True
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.70
    pre_nms_top_n: 1000
    post_nms_top_n: 1000


CascadeHead:
  head: CascadeTwoFCHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner

BBoxAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  cascade_iou: [0.5, 0.6, 0.7]
  use_random: True

CascadeTwoFCHead:
  out_channel: 1024

BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [30.0, 30.0, 15.0, 15.0]
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.04
    nms_threshold: 0.70  # bigger
    normalized: true

epoch: 20
LearningRate:
  base_lr: 0.005 # 4 GPU 0.005 8GPU 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [17, 19]
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0003
    type: L2


num_classes: 2
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train_class12.json
    dataset_dir: dataset/camera/PaddleDataset
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val_class12.json
    dataset_dir: dataset/camera/PaddleDataset



